// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEiH8JORmdrG5HbpOlKEqMwrkT0IG3wc',
    appId: '1:861160915653:web:1cacebdb673b15aea266ac',
    messagingSenderId: '861160915653',
    projectId: 'subleasier',
    authDomain: 'subleasier.firebaseapp.com',
    storageBucket: 'subleasier.appspot.com',
    measurementId: 'G-XS75NKXQXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBECgG3vdnk-FaX-pZE_7f2_7VHKSVce1o',
    appId: '1:861160915653:android:255350f09bbb321fa266ac',
    messagingSenderId: '861160915653',
    projectId: 'subleasier',
    storageBucket: 'subleasier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAMHCa3dmZGTOLdFW8cQPRw63dQQuW2k',
    appId: '1:861160915653:ios:bf99869b1321cdf7a266ac',
    messagingSenderId: '861160915653',
    projectId: 'subleasier',
    storageBucket: 'subleasier.appspot.com',
    iosBundleId: 'com.example.subleasier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGAMHCa3dmZGTOLdFW8cQPRw63dQQuW2k',
    appId: '1:861160915653:ios:bf99869b1321cdf7a266ac',
    messagingSenderId: '861160915653',
    projectId: 'subleasier',
    storageBucket: 'subleasier.appspot.com',
    iosBundleId: 'com.example.subleasier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnEiH8JORmdrG5HbpOlKEqMwrkT0IG3wc',
    appId: '1:861160915653:web:7423eb2be4b4185aa266ac',
    messagingSenderId: '861160915653',
    projectId: 'subleasier',
    authDomain: 'subleasier.firebaseapp.com',
    storageBucket: 'subleasier.appspot.com',
    measurementId: 'G-040L4CBCQE',
  );
}
